<div class="paragraph">
<p><code>InterruptedExceptions</code> should never be ignored in the code, and simply logging the exception counts in this case as "ignoring". The throwing of the <code>InterruptedException</code> clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, <code>InterruptedExceptions</code> should either be rethrown - immediately or after cleaning up the method&#8217;s state - or the thread should be re-interrupted by calling <code>Thread.interrupt()</code> even if this is supposed to be a single-threaded application. Any other course of action risks delaying thread shutdown and loses the information that the thread was interrupted - probably without finishing its task.</p>
</div>
<div class="paragraph">
<p>Similarly, the <code>ThreadDeath</code> exception should also be propagated. According to its JavaDoc:</p>
</div>
<div class="quoteblock">
<blockquote>
<div class="paragraph">
<p>If <code>ThreadDeath</code> is caught by a method, it is important that it be rethrown so that the thread actually dies.</p>
</div>
</blockquote>
</div>
<div class="sect1">
<h2 id="_noncompliant_code_example">Noncompliant Code Example</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>public void run () {
  try {
    while (true) {
      // do stuff
    }
  }catch (InterruptedException e) { // Noncompliant; logging is not enough
    LOGGER.log(Level.WARN, "Interrupted!", e);
  }
}</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_compliant_solution">Compliant Solution</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>public void run () {
  try {
    while (true) {
      // do stuff
    }
  }catch (InterruptedException e) {
    LOGGER.log(Level.WARN, "Interrupted!", e);
    // Restore interrupted state...
    Thread.currentThread().interrupt();
  }
}</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_see">See</h2>
<div class="sectionbody">
<div class="ulist">
<ul>
<li>
<p><a href="https://cwe.mitre.org/data/definitions/391.html">MITRE, CWE-391</a> - Unchecked Error Condition</p>
</li>
</ul>
</div>
<hr/>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Either re-interrupt this method or rethrow the "{InterruptedException/ThreadDeath}" that can be caught here.</p>
</div>
</div>
<div class="sect2">
<h3 id="_highlighting">Highlighting</h3>
<div class="ulist">
<ul>
<li>
<p>Primary: Catch parameter</p>
</li>
<li>
<p>Secondary: Method call throwing "InterruptedException"</p>
</li>
</ul>
</div>
<hr/>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_is_related_to_s5754">is related to: S5754</h3>

</div>
<div class="sect2">
<h3 id="_on_14_oct_2014_212147_freddy_mallet_wrote">on 14 Oct 2014, 21:21:47 Freddy Mallet wrote:</h3>
<div class="paragraph">
<p>@Ann, could you provide the source of this RSPEC because would like to double-check the main goal of this rule ? For sure here the code snippets are really misleading because we could have the feeling that when the execution of a Runnable class is interrupted, this exception can be caught in the <code>run</code> method which is not at all the case.</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_15_oct_2014_115938_ann_campbell_wrote">on 15 Oct 2014, 11:59:38 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>\[~freddy.mallet] https://twitter.com/aparnachaudhary/status/520952677631807488</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_4_sep_2019_203320_réda_housni_alaoui_wrote">on 4 Sep 2019, 20:33:20 Réda Housni Alaoui wrote:</h3>
<div class="paragraph">
<p>Hi,</p>
</div>
<div class="paragraph">
<p>I think the rule derived from this spec is too narrow.</p>
</div>
<div class="literalblock">
<div class="content">
<pre>Many people write ``++catch (Exception e)++`` in their applications.</pre>
</div>
</div>
<div class="paragraph">
<p>Following this spec, IMO, that means that any <code>catch(Exception e)</code> must ALWAYS be preceded by a catch of InterruptedException like this</p>
</div>
<div class="listingblock">
<div class="content">
<pre>catch (InterruptedException e) {
  Thread.currentThread().interrupt();
} catch (Exception e) {
  //...
}{code}</pre>
</div>
</div>
</div>
</div>
</div>